<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-418NQCC" ignored="2" name="Default test(failed)" tests="6" failures="1" timestamp="21 Nov 2022 17:09:34 GMT" time="0.25" errors="0">
  <testcase name="@AfterMethod aftermethod" time="0.031" classname="org.test.rerun.RerunTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at org.base.BaseClass.screenshot(BaseClass.java:271)
at org.test.rerun.RerunTest.aftermethod(RerunTest.java:38)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod aftermethod -->
  <testcase name="test3" time="0.031" classname="org.test.rerun.RerunTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.016" classname="org.test.rerun.RerunTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.016" classname="org.test.rerun.RerunTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="org.test.rerun.RerunTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.016" classname="org.test.rerun.RerunTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.016" classname="org.test.rerun.RerunTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.test.rerun.RerunTest.test3(RerunTest.java:29)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="org.test.rerun.RerunTest">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="org.test.rerun.RerunTest">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- Default test(failed) -->
